# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6_m.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab6_m.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clab6_m.proto\"\x1e\n\x06\x41\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x10\n\x03Sum\x12\t\n\x01s\x18\x01 \x01(\x05\"\x17\n\x08ImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\x04Size\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x45\n\x04lab6\x12\x1c\n\tGetAddMsg\x12\x07.AddMsg\x1a\x04.Sum\"\x00\x12\x1f\n\tGetImgMsg\x12\t.ImageMsg\x1a\x05.Size\"\x00\x62\x06proto3'
)




_ADDMSG = _descriptor.Descriptor(
  name='AddMsg',
  full_name='AddMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='AddMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='AddMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=46,
)


_SUM = _descriptor.Descriptor(
  name='Sum',
  full_name='Sum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='Sum.s', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=64,
)


_IMAGEMSG = _descriptor.Descriptor(
  name='ImageMsg',
  full_name='ImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='ImageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=89,
)


_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='Size.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='Size.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['AddMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['Sum'] = _SUM
DESCRIPTOR.message_types_by_name['ImageMsg'] = _IMAGEMSG
DESCRIPTOR.message_types_by_name['Size'] = _SIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddMsg = _reflection.GeneratedProtocolMessageType('AddMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'lab6_m_pb2'
  # @@protoc_insertion_point(class_scope:AddMsg)
  })
_sym_db.RegisterMessage(AddMsg)

Sum = _reflection.GeneratedProtocolMessageType('Sum', (_message.Message,), {
  'DESCRIPTOR' : _SUM,
  '__module__' : 'lab6_m_pb2'
  # @@protoc_insertion_point(class_scope:Sum)
  })
_sym_db.RegisterMessage(Sum)

ImageMsg = _reflection.GeneratedProtocolMessageType('ImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMSG,
  '__module__' : 'lab6_m_pb2'
  # @@protoc_insertion_point(class_scope:ImageMsg)
  })
_sym_db.RegisterMessage(ImageMsg)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), {
  'DESCRIPTOR' : _SIZE,
  '__module__' : 'lab6_m_pb2'
  # @@protoc_insertion_point(class_scope:Size)
  })
_sym_db.RegisterMessage(Size)



_LAB6 = _descriptor.ServiceDescriptor(
  name='lab6',
  full_name='lab6',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=130,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAddMsg',
    full_name='lab6.GetAddMsg',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_SUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetImgMsg',
    full_name='lab6.GetImgMsg',
    index=1,
    containing_service=None,
    input_type=_IMAGEMSG,
    output_type=_SIZE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAB6)

DESCRIPTOR.services_by_name['lab6'] = _LAB6

# @@protoc_insertion_point(module_scope)
