# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lab6_m_pb2 as lab6__m__pb2


class lab6Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAddMsg = channel.unary_unary(
                '/lab6/GetAddMsg',
                request_serializer=lab6__m__pb2.AddMsg.SerializeToString,
                response_deserializer=lab6__m__pb2.Sum.FromString,
                )
        self.GetImgMsg = channel.unary_unary(
                '/lab6/GetImgMsg',
                request_serializer=lab6__m__pb2.ImageMsg.SerializeToString,
                response_deserializer=lab6__m__pb2.Size.FromString,
                )


class lab6Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAddMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImgMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_lab6Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAddMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddMsg,
                    request_deserializer=lab6__m__pb2.AddMsg.FromString,
                    response_serializer=lab6__m__pb2.Sum.SerializeToString,
            ),
            'GetImgMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImgMsg,
                    request_deserializer=lab6__m__pb2.ImageMsg.FromString,
                    response_serializer=lab6__m__pb2.Size.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab6', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class lab6(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAddMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6/GetAddMsg',
            lab6__m__pb2.AddMsg.SerializeToString,
            lab6__m__pb2.Sum.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImgMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6/GetImgMsg',
            lab6__m__pb2.ImageMsg.SerializeToString,
            lab6__m__pb2.Size.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
